# Site settings
title: Stanley Yang
email: me@stanleycyang.com
description: > # this means to ignore newlines until "baseurl:"
  A compilation of my knowledge and opinions on technology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stanleycyang.github.io" # the base hostname & protocol for your site
twitter_username: StanleyCYang
github_username:  stanleycyang

# Build settings
markdown: kramdown

# gems
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
