# Site settings
title: Stanley Yang
email: stanley@stanleycyang
description: > # this means to ignore newlines until "baseurl:"
  A compilation of experiences and opinions on technology and life from a lifelong learner
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: StanleyCYang
github_username:  stanleycyang

# Build settings
markdown: kramdown
